let users = [];
let categories = [];
let tasks = [];
let subtasks = [];
let colors = ['#8AA4FF','#FF0000','#2AD300','#FF8A00','#E200BE','#0038FF'];
let urgentColor = 'background-color: #FF3D00; color: #FFFFFF;';
let mediumColor = 'background-color: #FFA800;color: #FFFFFF;';
let lowColor = 'background-color: #7AE229;color: #FFFFFF;';
let activeID = '';
let activeImg = '';
let selectedCategory;
let dropDownCat = false;
let dropDownAssign = false;
let assigned = [];
let loggedIn = false;
let indexOfEmail = [];
let today = new Date().toISOString().split('T')[0];